HAL_Se1: FLASH Public Functions
FLASH Public Functions
FLASH
Functions
void FLASH_Init ()
Initialises the FLASH API.
unsigned int FLASH_EraseSector (unsigned int sector)
Erases a sector in flash memory.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Write the data from srcAddr of size bytes to the address inside the FLASH memory pointed by dstAddr.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares the content pointed by srcAddr of size bytes with the content pointed by dstAddr inside a FLASH region.
Detailed Description
Function Documentation
FLASH_EraseSector()
unsigned int FLASH_EraseSector (unsigned int sector)
Erases a sector in flash memory.
Parameters
sector The sector number to be erased.
Returns
status code
Definition at line 15 of file FLASH.c.
References _FLASH_ClearCommandsAndOutput(), and _FLASH_PrepareSectorForWrite().
FLASH_Init()
void FLASH_Init ()
Initialises the FLASH API.
Note
This function must be called prior to any other FLASH functions.
Definition at line 10 of file FLASH.c.
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Compares the content pointed by srcAddr of size bytes with the content pointed by dstAddr inside a FLASH region.
Parameters
dstAddr address inside a FLASH region to compare the data to
srcAddr address containing the data
size size of data
Definition at line 89 of file FLASH.c.
References _FLASH_ClearCommandsAndOutput().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Write the data from srcAddr of size bytes to the address inside the FLASH memory pointed by dstAddr.
Parameters
dstAddr address inside a FLASH region to write the data to
srcAddr address containing the data
size size of data
Returns
status code
Definition at line 33 of file FLASH.c.
References _FLASH_GetSector(), and _FLASH_PrepareSectorForWrite().