HAL_Se1: LCDText Public Functions
LCDText Public Functions
LCDText
Functions
void LCDText_Init ()
Initialises the LCD API with 2 lines, 16 columns and blinking cursor.
void LCDText_WriteChar (char ch)
Writes a char to the LCD screen.
void LCDText_WriteString (char *str)
Writes a string of chars to the LCD screen.
void LCDText_SetCursor (int row, int column)
Changes the cursor position on the LCD screen.
void LCDText_Clear ()
Clears the LCD screen and resets cursor position.
Detailed Description
Function Documentation
LCDText_Init()
void LCDText_Init ()
Initialises the LCD API with 2 lines, 16 columns and blinking cursor.
Note
This function must be called prior to any other LCDText functions.
Definition at line 13 of file LCDText.c.
References WAIT_ChronosInit().
LCDText_SetCursor()
void LCDText_SetCursor (int row, int column)
Changes the cursor position on the LCD screen.
Parameters
row,column new cursor position
Definition at line 58 of file LCDText.c.
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a char to the LCD screen.
Parameters
ch Char to be written.
Note
The cursor will be updated automatically after the char is written.
Definition at line 123 of file LCDText.c.
References __LCD_Write9Bits().
Referenced by LCDText_WriteString().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string of chars to the LCD screen.
Parameters
str C-String to be written.
Note
The cursor will be updated automatically after each char is written.
Definition at line 152 of file LCDText.c.
References LCDText_WriteChar().