HAL_Se1: LCDText Private Functions
LCDText Private Functions
LCDText
Functions
void __LCD_Write5Bits (bool rs, int8_t data)
Sends 4 bits to the LCD.
void __LCD_Write9Bits (bool rs, int8_t data)
Sends 8 bits to the LCD.
void PULSE_ENABLE ()
Toggles the enable signal.
Detailed Description
Function Documentation
__LCD_Write5Bits()
void __LCD_Write5Bits (bool rs, int8_t data)
Sends 4 bits to the LCD.
Parameters
rs Indicates whether the bits being sent are part of a command or data
data Bits to send to the LCD
Definition at line 113 of file LCDText.c.
Referenced by __LCD_Write9Bits().
__LCD_Write9Bits()
void __LCD_Write9Bits (bool rs, int8_t data)
Sends 8 bits to the LCD.
Parameters
rs Indicates whether the bits being sent are part of a command or data
data Bits to send to the LCD
Definition at line 107 of file LCDText.c.
References __LCD_Write5Bits().
Referenced by LCDText_Clear(), and LCDText_WriteChar().