HAL_Se1: SPI Public Functions
SPI Public Functions
SPI
Functions
void SPI_Init ()
Initialises the SPI API.
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Used to configure the transfer.
int SPI_Transfer (unsigned short *txBuffer, unsigned short *rxBuffer, int length)
Used to transfer in and out.
Detailed Description
Function Documentation
SPI_ConfigTransfer()
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Used to configure the transfer.
Parameters
frequency The frequency at which the transfer operates.
bitData The length in bits to transfer.
mode Configure the SPI Data To Clock Phase Relationship.
Definition at line 73 of file SPI.c.
Referenced by BMP_Init().
SPI_Init()
void SPI_Init ()
Initialises the SPI API.
Note
This function must be called prior to any other SPI functions.
Definition at line 48 of file SPI.c.
Referenced by BMP_Init().
SPI_Transfer()
int SPI_Transfer (unsigned short * txBuffer, unsigned short * rxBuffer, int length)
Used to transfer in and out.
Parameters
txBuffer Pointer to a buffer of shorts that will be transfered out.
rxBuffer Pointer to the destination buffer where the contents will be read to.
length length in number of shorts to be read or written.
Definition at line 92 of file SPI.c.
Referenced by GetReg16(), GetReg8(), and SetReg8().