HAL_Se1: FLASH Private Functions
FLASH Private Functions
FLASH
Functions
void _FLASH_ClearCommandsAndOutput ()
Clears the command and output buffer.
unsigned int _FLASH_GetSector (void *addr)
Get the sector number that contains the given address.
unsigned int _FLASH_PrepareSectorForWrite (unsigned int startSector, unsigned int endSector)
Prepare a FLASH section to be written.
Detailed Description
Function Documentation
_FLASH_GetSector()
unsigned int _FLASH_GetSector (void * addr)
Get the sector number that contains the given address.
Parameters
addr address inside a FLASH sector
Definition at line 75 of file FLASH.c.
Referenced by FLASH_WriteData().
_FLASH_PrepareSectorForWrite()
unsigned int _FLASH_PrepareSectorForWrite (unsigned int startSector, unsigned int endSector)
Prepare a FLASH section to be written.
Parameters
startSector start sector
endSector end sector
Definition at line 55 of file FLASH.c.
References _FLASH_ClearCommandsAndOutput().
Referenced by FLASH_EraseSector(), and FLASH_WriteData().