HAL_Se1: BMP Public Functions
BMP Public Functions
BMP
Functions
void BMP_Init ()
Initialises communication with the BMP sensor.
int SetReg8 (unsigned short registerName, unsigned short value)
Sets a register in the BMP sensor with the given value.
unsigned short GetReg16 (unsigned short registerName)
Get the value of a 16bit register from the BMP sensor.
unsigned char GetReg8 (unsigned char registerName)
Get the value of a 8bit register from the BMP sensor.
Detailed Description
Function Documentation
BMP_Init()
void BMP_Init ()
Initialises communication with the BMP sensor.
Note
This function must be called prior to any other BMP functions
Definition at line 71 of file BMP.c.
References SPI_ConfigTransfer(), and SPI_Init().
GetReg16()
unsigned short GetReg16 (unsigned short registerName)
Get the value of a 16bit register from the BMP sensor.
Parameters
registerName the register to get the value from
Definition at line 31 of file BMP.c.
References SPI_Transfer().
GetReg8()
unsigned char GetReg8 (unsigned char registerName)
Get the value of a 8bit register from the BMP sensor.
Parameters
registerName the register to get the value from
Definition at line 51 of file BMP.c.
References SPI_Transfer().
SetReg8()
int SetReg8 (unsigned short registerName, unsigned short value)
Sets a register in the BMP sensor with the given value.
Parameters
registerName the register to write the data to
value the value to write to the register
Returns
Status
Definition at line 12 of file BMP.c.
References SPI_Transfer().